from pydantic import BaseModel, Field


class Task(BaseModel):
    """
    Represents the user's original request.
    """

    request: str = Field(  # ال request لطلب المستخدم
        ...,
        description="Original user request",  # الوصف لل documentation وIDE ,OpenAPI
    )
    # دلوقتي بعد task دي ال planner هيطلع plan مش string


class Step(BaseModel):
    """
    Represents a single execution step in a plan.
    """

    description: str = Field(
        ...,
        description="Description of the step",
    )

    status: str = Field(
        default="pending",
        description="Execution status",
    )


class Plan(BaseModel):
    """
    Execution plan generated by the Planner Agent.
    """

    steps: list[Step] = Field(
        default_factory=list,
        description="Ordered execution steps",
    )

    status: str = Field(
        default="pending",
        description="Plan status",
    )


class CodeArtifact(BaseModel):
    """
    Code generated by the Developer Agent.
    """

    content: str = Field(
        default="",
        description="Generated code",
    )

    language: str = Field(
        default="python",
        description="Programming language",
    )


class Review(BaseModel):
    """
    Review result generated by the Reviewer Agent.
    """

    approved: bool = False

    feedback: str = ""

    score: int = 0
